language: php

php:
  - 7.1

sudo: false

before_install:
  - cp .env.example .env

install: travis_retry composer install --no-interaction --no-scripts --prefer-source --no-suggest

script:
  - vendor/bin/phpunit --verbose

matrix:
  allow_failures:
    - php: hhvm
